version: 2

formats:
  - pdf

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  apt_packages:
    - libopenmpi-dev

python:
  install:
    - requirements: docs/requirements_doc.txt
    - method: pip
      path: .
